// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // src/app/layout.tsx (inside <head>)
// <script
//   async
//   src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-XXXXXXXXXXXXXXXX"
//   crossOrigin="anonymous"
// />


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// import "./globals.css";

// export const metadata = { title: "Brainrot Craft" };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="bg-gradient-to-b from-zinc-900 to-black text-white">
//         {children}
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Anycraft – Brainrot Craft",
//   description: "Craft elements to discover brainrot characters",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     // Let React ignore attribute diffs injected by extensions (e.g., cz-shortcut-listen)
//     <html lang="en" suppressHydrationWarning>
//       <body
//         suppressHydrationWarning
//         className="bg-gradient-to-b from-zinc-900 to-black text-white"
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import Script from "next/script";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "ANYCRAFT",
//   description: "Combine elements. Unlock surprises.",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         {children}

//         {/* Google AdSense global script (needed for review + ads) */}
//         <Script
//           id="adsense-script"
//           async
//           src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2110509679283065"
//           crossOrigin="anonymous"
//           strategy="afterInteractive"
//         />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "ANYCRAFT",
  description: "Combine elements. Unlock surprises.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // keep old behavior
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className="bg-gradient-to-b from-zinc-900 to-black text-white"
      >
        {children}

        {/* Google AdSense global script (needed for review + ads) */}
        <Script
          id="adsense-script"
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2110509679283065"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
